/* AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by scripts/tilesets/generate-tileset-manifest.mjs
 */

export type GeneratedTilesetManifestEntry = {
  readonly label: string;
  readonly path: string;
  readonly tileSize: number;
};

export const GENERATED_TILESET_MANIFEST: ReadonlyArray<GeneratedTilesetManifestEntry> =
  [
  {
    "label": "DawnHack",
    "path": "assets/3.6/DawnHack.bmp",
    "tileSize": 32
  },
  {
    "label": "Nevanda 3.6",
    "path": "assets/3.6/Nevanda 3.6.png",
    "tileSize": 32
  }
] as const;
